# Supported funding model platforms for ReKameo.
# Fill in whichever are relevant before pushing the repo.

github: # [user1, user2]
patreon: # single Patreon username
open_collective: # single Open Collective username
ko_fi: # single Ko-fi username
custom: # ['link1', 'link2']
